product:
    resource: "@AcmeStoreBundle/Controller/DefaultController.php"
    type:     annotation

task_new:

        resource: "@AcmeStoreBundle/Controller/DefaultController.php"
        type:     annotation
