parameters:
#    acme_user.example.class: Acme\UserBundle\Example

services:
#    acme_user.example:
#        class: %acme_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    acme_user.password_resetting:
            class: Acme\UserBundle\EventListener\PasswordResettingListener
            arguments: [@router]
            tags:
                - { name: kernel.event_subscriber }

    app.form.registration:
            class: Acme\UserBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }